/*
 * File: app/store/Leads.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Exxica.store.Leads', {
    extend: 'Ext.data.Store',

    requires: [
        'Exxica.model.Lead',
        'Ext.data.proxy.Direct',
        'Exxica.DirectAPI',
        'Ext.data.reader.Json',
        'Ext.data.writer.Json',
        'Ext.util.Grouper'
    ],

    config: {
        autoSync: true,
        model: 'Exxica.model.Lead',
        storeId: 'Leads',
        proxy: {
            type: 'direct',
            api: {
                create: 'Leads.create',
                read: 'Leads.read',
                update: 'Leads.update',
                destroy: 'Leads.destroy'
            },
            reader: {
                type: 'json',
                idProperty: 'idLead',
                messageProperty: 'message',
                rootProperty: 'data'
            },
            writer: {
                type: 'json'
            }
        },
        sorters: {
            property: 'lastName'
        },
        grouper: {
            groupFn: function(item) {
                return item.get('lastName')[0];
            }
        }
    }
});