/*
 * File: app/store/MapStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Exxica.store.MapStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Exxica.model.MapModel',
        'Ext.data.proxy.JsonP',
        'Ext.data.reader.Json'
    ],

    config: {
        model: 'Exxica.model.MapModel',
        storeId: 'MapStore',
        proxy: {
            type: 'jsonp',
            enablePagingParams: false,
            extraParams: {
                key: 'AIzaSyBZVt-x2xIL30xX_WyLEy9VdLYU01epQhw'
            },
            url: 'https://maps.googleapis.com/maps/api/geocode/json',
            reader: {
                type: 'json',
                rootProperty: 'results',
                successProperty: 'status'
            }
        }
    }
});