/*
 * File: app/model/Lead.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Exxica.model.Lead', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        idProperty: 'idLead',
        fields: [
            {
                name: 'idLead',
                type: 'int'
            },
            {
                name: 'fkContact',
                type: 'int'
            },
            {
                name: 'fkCompany',
                type: 'int'
            },
            {
                name: 'fkLicence',
                type: 'int'
            },
            {
                name: 'fkRating',
                type: 'int'
            },
            {
                name: 'fkFollowupType',
                type: 'int'
            },
            {
                name: 'fkVisibility',
                type: 'int'
            },
            {
                name: 'fkSalesman',
                type: 'int'
            },
            {
                name: 'fkAcquisitionSource',
                type: 'int'
            },
            {
                name: 'followupTypeIcon',
                type: 'string'
            },
            {
                name: 'followupTimePrefix',
                type: 'int'
            },
            {
                name: 'followupDateTime',
                type: 'date'
            },
            {
                name: 'followupNote',
                type: 'string'
            },
            {
                name: 'contactType',
                type: 'int'
            },
            {
                name: 'ratingInt',
                type: 'int'
            },
            {
                name: 'ratingStr',
                type: 'string'
            },
            {
                name: 'ratingStyle',
                type: 'string'
            },
            {
                name: 'fullName',
                type: 'string'
            },
            {
                name: 'firstName',
                type: 'string'
            },
            {
                name: 'middleName',
                type: 'string'
            },
            {
                name: 'lastName',
                type: 'string'
            },
            {
                name: 'postAdress',
                type: 'string'
            },
            {
                name: 'postZip',
                type: 'string'
            },
            {
                name: 'postTown',
                type: 'string'
            },
            {
                name: 'contactPhone',
                type: 'string'
            },
            {
                name: 'contactMail',
                type: 'string'
            },
            {
                name: 'note',
                type: 'string'
            },
            {
                name: 'trashFlag',
                type: 'int'
            },
            {
                name: 'customerOrLead',
                type: 'int'
            },
            {
                name: 'skypeHandle',
                type: 'string'
            },
            {
                name: 'facebookUrl',
                type: 'string'
            },
            {
                name: 'googleUrl',
                type: 'string'
            },
            {
                name: 'linkedinUrl',
                type: 'string'
            },
            {
                name: 'photoUrl',
                type: 'string'
            }
        ]
    }
});