/*
 * File: app/controller/Account.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Exxica.controller.Account', {
    extend: 'Ext.app.Controller',

    config: {
        models: [
            'User',
            'Lead'
        ],
        stores: [
            'Account',
            'Leads'
        ],
        views: [
            'LoginForm'
        ],

        refs: {
            mainView: 'mainview',
            loginForm: 'loginform',
            leadsPanel: 'leadspanel'
        },

        control: {
            "loginform #loginButton": {
                tap: 'login'
            }
        }
    },

    login: function(button, e, eOpts) {
        var me = this;
        var form = me.getLoginForm(),
            values = form.getValues(),
            leads = me.getLeadsPanel();

        // Success
        var successCallback = function(resp, ops) {
            var accountStore = Ext.getStore('Account');
            var User = Ext.ModelMgr.getModel('Exxica.model.User');
            var xhr = Ext.JSON.decode(resp.responseText);
            var data = xhr.data;
            //var leadsStore = Ext.getStore('Leads');

            if(xhr.success) {
                var account = Ext.create(User, {
                    controlKey: data._c,
                    idCompany: data.company_id,
                    idUser: data.user_id,
                    idLicence: data.licence_id,
                    language: data.language
                });
                accountStore.add(account);

                /*leadsStore.getProxy().setExtraParams({
                    "licenceid" account.get('idLicence'),
                    "companyid": account.get('idCompany'),
                    "userid": account.get('idUser'),
                    "isBin": false
                });*/
                //console.log(leadsStore);
                //leadsStore.load();

                form.hide();
                leads.show();
            }
        };

        // Failure
        var failureCallback = function(resp, ops) {
            var xhr = Ext.JSON.decode(resp.responseText);

            Ext.MsgBox.alert("Login failed", xhr.data.message);
        };


        Ext.Ajax.request({
            url: "http://localhost/cloud/api/index.php?r=mobile/login",
            params: values,
            success: successCallback,
            failure: failureCallback
        });
    }

});