/*
 * File: app/controller/LeadEdit.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Exxica.controller.LeadEdit', {
    extend: 'Ext.app.Controller',

    config: {
        models: [
            'User',
            'Lead'
        ],
        stores: [
            'Account',
            'Leads'
        ],
        views: [
            'LeadEdit'
        ],

        refs: {
            PhotoContainer: 'image#LeadEdit_ImageContainer_Photo'
        },

        control: {
            "button#LeadEdit_ImageContainer_Actions_Library": {
                tap: 'onPhotoLibraryTap'
            },
            "button#LeadEdit_ImageContainer_Actions_Camera": {
                tap: 'onTakePhotoTap'
            },
            "formpanel#leadEdit": {
                change: 'onLeadEditChange'
            }
        }
    },

    onPhotoLibraryTap: function(button, e, eOpts) {
        var me = this;
        me.getPhotoContainer().getPhoto(navigator.camera.PictureSourceType.PHOTOLIBRARY);
    },

    onTakePhotoTap: function(button, e, eOpts) {
        var me = this;
        me.getPhotoContainer().getPhoto(navigator.camera.PictureSourceType.CAMERA);
    },

    onLeadEditChange: function(formpanel) {
        this.showSaveButton();
    },

    getPhoto: function(source) {
        var me = this;

        navigator.camera.getPicture(me.success, me.failure, {
            quality: 50,
            destinationType: navigator.camera.DestinationType.FILE_URI,
            sourceType: source
        });
    },

    success: function(image_url) {
        var me = this;
        me.getPhotoContainer().setSrc(image_uri);
    },

    failure: function(message) {
        alert("Failed" + message);
    }

});