/*
 * File: app/controller/LeadShow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Exxica.controller.LeadShow', {
    extend: 'Ext.app.Controller',

    config: {
        models: [
            'MapModel',
            'Lead',
            'User'
        ],
        stores: [
            'MapStore',
            'Leads',
            'LeadView',
            'Account'
        ],
        views: [
            'LeadShow',
            'RoadMap'
        ],

        refs: {
            content: 'dataview#leadContent',
            roadMap: 'map#leadMap',
            leadEdit: 'formpanel#leadEdit'
        }
    },

    updateRecord: function(newRecord) {
        var me = this;
        if(newRecord) {
            var contentStore = me.getContent().getStore();
            contentStore.removeAll();
            contentStore.add(newRecord);
            me.getRoadMap().setMapCenter({
                latitude: newRecord.data.latitude,
                longitude: newRecord.data.longitude
            });
        }
    }

});