/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Exxica.controller.Main', {
    extend: 'Ext.app.Controller',

    config: {
        views: [
            'MainView'
        ],

        refs: {
            editButton: 'button#editButton',
            saveButton: 'button#saveButton',
            leads: 'list#leadsList',
            leadEdit: 'leadEdit',
            leadShow: 'leadShow',
            mainView: 'navigationview#mainView',
            settingsButton: 'button#settingsButton',
            addButton: 'button#addButton'
        },

        control: {
            "navigationview#mainView": {
                push: 'onMainPush',
                pop: 'onMainPop'
            },
            "button#saveButton": {
                tap: 'onSaveTap'
            },
            "button#editButton": {
                tap: 'onEditTap'
            }
        }
    },

    onMainPush: function(navigationview, view, eOpts) {
        var me = this;
        var editButton = me.getEditButton();

        if (view.xtype == "leadShow") {
            me.getLeads().deselectAll();

            me.showEditButton();
        } else {
            me.hideEditButton();
        }
    },

    onMainPop: function(navigationview, view, eOpts) {
        var me = this;

        if (view.xtype == "leadEdit") {
            me.showEditButton();
        } else {
            me.hideEditButton();
        }
    },

    onSaveTap: function(button, e, eOpts) {
        var record = this.getLeadEdit().saveRecord();

        this.getLeadShow().updateRecord(record);

        this.getMainView().pop();
    },

    onEditTap: function(button, e, eOpts) {
        var me = this;

        if (!me.editLead) {
            me.editLead = Ext.create('Exxica.view.LeadEdit');
        }

        me.editLead.setRecord(me.getLeadShow().getRecord());

        me.getMainView().push(me.editLead);
    },

    showEditButton: function() {
        var editButton = this.getEditButton();

        if (!editButton.isHidden()) {
            return;
        }

        this.hideSaveButton();

        editButton.show();
    },

    hideEditButton: function() {
        var editButton = this.getEditButton();

        if (editButton.isHidden()) {
            return;
        }

        editButton.hide();
    },

    showSettingsButton: function() {
        var settingsButton = this.getSettingsButton();

        if (!settingsButton.isHidden()) {
            return;
        }

        this.hideSaveButton();
        this.hideEditButton();

        settingsButton.show();
    },

    hideSettingsButton: function() {
        var settingsButton = this.getSettingsButton();

        if (settingsButton.isHidden()) {
            return;
        }

        settingsButton.hide();
    },

    showAddButton: function() {
        var addButton = this.getAddButton();

        if (!addButton.isHidden()) {
            return;
        }

        this.hideSaveButton();
        this.hideEditButton();

        addButton.show();
    },

    hideAddButton: function() {
        var addButton = this.getAddButton();

        if (addButton.isHidden()) {
            return;
        }

        addButton.hide();
    },

    showSaveButton: function() {
        var saveButton = this.getSaveButton();

        if (!saveButton.isHidden()) {
            return;
        }

        saveButton.show();
    },

    hideSaveButton: function() {
        var saveButton = this.getSaveButton();

        if (saveButton.isHidden()) {
            return;
        }

        saveButton.hide();
    }

});