/*
 * File: app/view/LeadsList.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Exxica.view.LeadsList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.leadsList',

    requires: [
        'Ext.XTemplate',
        'Ext.plugin.PullRefresh'
    ],

    config: {
        cls: 'x-contacts',
        height: '100%',
        itemId: 'leadsList',
        emptyText: 'No leads found...',
        loadingText: 'Loading leads...',
        store: 'Leads',
        grouped: true,
        itemHeight: 50,
        refreshHeightOnUpdate: false,
        variableHeights: true,
        hideAnimation: {
            type: 'fadeOut',
            duration: 200
        },
        showAnimation: {
            type: 'fadeIn',
            duration: 200
        },
        itemTpl: [
            '<div class="headshot" style="background-image:{photoUrl};"></div>',
            '{lastName}, {firstName} {middleName}',
            '<span>',
            '    Tel: {contactPhone}',
            '</span>'
        ],
        plugins: [
            {
                type: 'pullrefresh'
            }
        ]
    }

});