/*
 * File: app/view/LeadsPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Exxica.view.LeadsPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.leadspanel',

    requires: [
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        itemId: 'leadsPanel',
        autoDestroy: false,
        layout: 'fit',
        scrollable: 'vertical',
        items: [
            {
                xtype: 'list',
                cls: 'x-contacts',
                itemId: 'leadsList',
                itemTpl: [
                    '<div class="headshot" style="background-image:{photoUrl};"></div>',
                    '{lastName}, {firstName}',
                    '<span>{title}</span>'
                ],
                store: 'Leads',
                variableHeights: true
            }
        ]
    }

});